class ApplicationController < ActionController::Base
  before_action :hey
  def hey
    @solve={"1":"1 + what equals 2",
    "2":"4 minus 2 equals ",
    "3":"9 divided by 3 equals",
    "4":"2 times 2 equals",
    "5":"25 divided by 5 equals",
    "6":"12 divided by what equals 2",
    "7":"3 plus 4 equals",
    "8":"four times 2 equals",
    "9":"four plus five equals",
    "10":"2 times 5 equals",
    "11":"five plus six equals",
    "l":"leaf",
    "m":"mitten",
    "n":"nest",
    "o":"oven",
    "p":"pizza",
    "q":"quarter",
    "r":"rabbit",
    "s":"sock",
    "t":"turkey",
    "u":"umbrella",
    "v":"vest",
    "w":"watch",
    "x":"x-ray",
    "y":"yo-yo",
    "z":"zipper"
    }
    @alphabet={"a":"apple",
    "b":"ball",
    "c":"car",
    "d":"duck",
    "e":"eggplant",
    "f":"fire",
    "g":"goat",
    "h":"hamburger",
    "i":"inch",
    "j":"jelly",
    "k":"kite",
    "l":"leaf",
    "m":"mitten",
    "n":"nest",
    "o":"oven",
    "p":"pizza",
    "q":"quarter",
    "r":"rabbit",
    "s":"sock",
    "t":"turkey",
    "u":"umbrella",
    "v":"vest",
    "w":"watch",
    "x":"x-ray",
    "y":"yo-yo",
    "z":"zipper"
    }
  end
end
