class ApplicationController < ActionController::Base
  before_action :hey
  def hey
    @solve={"1":"1 + something equals 2",
    "2":"4 minus 2 equals ",
    "3":"9 divided by 3 equals",
    "4":"2 times 2 equals",
    "5":"25 divided by 5 equals",
    "6":"12 divided by something equals 2",
    "7":"3 plus 4 equals",
    "8":"four times 2 equals",
    "9":"four plus five equals",
    "10":"2 times 5 equals",
    "11":"five plus six equals",
    "12":"six plus six equals",
    "13":"20 minus seven equals",
    "14":"two times seven equals",
    "15":"thirty divided by two equals",
    "16":"four times four equals",
    "17":"elevel plus six equals",
    "18":"nine plus nine equals",
    "19":"eighteen plus 1 equals",
    "20":"ten + ten equals",
    "21":"nine plus something equals thirty",
    "22":"thirty minus something equals eight",
    "23":"something plus two equals twenty five",
    "24":"two times twelve equals",
    "25":"five times five equals",
    "26":"twenty four plus two equals"
    }
    @alphabet={"a":"apple",
    "b":"ball",
    "c":"car",
    "d":"duck",
    "e":"eggplant",
    "f":"fire",
    "g":"goat",
    "h":"hamburger",
    "i":"inch",
    "j":"jelly",
    "k":"kite",
    "l":"leaf",
    "m":"mitten",
    "n":"nest",
    "o":"oven",
    "p":"pizza",
    "q":"quarter",
    "r":"rabbit",
    "s":"sock",
    "t":"turkey",
    "u":"umbrella",
    "v":"vest",
    "w":"watch",
    "x":"x-ray",
    "y":"yo-yo",
    "z":"zipper"
    }
    @poems={"a":"Apples, apples Growing on a tree. Apples, apples Pick one just for me! One apple, two apples, Three apples, four. Red apples, green apples, Yellow apples, more! Apples, apples Tasty as can be. Apples, apples Share one now with me!",
    "b":"Roll it, toss it, catch it high, Bounce it low or watch it fly, Round and fun, big or small, Everyone loves playing with a ball.",
    "c":"A car is a car, If it can ride you nearby or far, A car is a car, When it gets you in time to the bar, A car is a car, When you are addressed as Madam or Sir, But for some, A car is not just a car",
    "d":"Quack! Quack! Quack! Ok, where’s everybody? I’ve been gliding round in this pond the last half hour singing my Duck-thoven tunes: Quack! Quack! Quack! Quack! Quack! Quack! And so why’s everyone avoiding me like I don’t know how to make conversation? Quack? Quack?",
    "e":"Purple looks like a mid-night sky, Purple sounds like a purple violin playing a melody, Purple smells like fresh, homemade eggplant out of the oven, Purple tastes like heart made eggplant in your mouth",
    "f":"That fearful sound of fire and fire, Let no man know is my Desire. I, starting up, the light did spy, And to my God my heart did cry To straighten me in my Distress And not to leave me succourless ",
    "g":"Down in the reeds by the river? Spreading ruin and scattering ban  Splashing and paddling with hoofs of a goat  And breaking the golden lilies afloat 5  With the dragon-fly on the river. ",
    "h":"Have you ever been awaken From the best sleep ever When your eyes could hardly open And you could barely speak, Have you ever had a partner Whom with everthing clicked But you quit, Have you ever been eating a hamburger while driving and you saw something, And out the window it went",
    "i":"If you were only one inch tall, you'd ride a worm to school. The teardrop of a crying ant would be your swimming pool. A crumb of cake would be a feast  And last you seven days at least, A flea would be a frightening beast If you were one inch tall.",
    "j":"Your hands are cream, They rub into me, Filling my skin with content, Your eyes are chocolate, They melt my gaze, My mouth goes dry with want, Your heart is jelly, I wish to take a bite, Would you let me, even if my teeth leave a mark?",
    "k":"How bright on the blue Is a kite when it’s new! With a dive and a dip It snaps its tail",
    "l":"The one red leaf, the last of its clan, That dances as often as dance it can, Hanging so light, and hanging so high, On the topmost twig that looks up at the sky.",
    "m":"Stripes or dots or sparkling white, Mittens in winter fit just right. Wool and cotton, maybe leather- Mittens warm us in cold weather. In rainbow colors and darkest black, Mittens fit in a pocket or in your pack. Thumbs alone, fingers together, We love mittens in cold, cold weather.",
    "n":"I walked out, and the nest was already there by the step.  Woven basket of a saint sent back to life as a bird who proceeded to make a mess of things.  Wind right through it, and any eggs long vanished.  But in my hand it was intricate pleasure, even the thorny reeds softened in the weave.  And the fading leaf mold, hardly itself anymore, merely a trick of light, if light can be tricked.  Deep in a life is another life.  I walked out, the nest already by the step.",
    "o":"If I were an oven, I would cook cake and Thanksgiving turkey, And you would notice my heat Just as you notice the hum of the refrigerator, The smell of my meatloaf, And the glow of the stove as you make breakfast. ",
    "p":"How you fill my heart with joy! Your cheesy goodness, Your savory sauce, I can’t get enough of you. Oh, beautiful pizza, You are my comfort food.",
    "q":"Down there in winter In Landstrasse quarters Blankets of clouds And the streets filled with waters, Darkness covers the city In the hours of night, And no bird, Seems to be there, Or live there abide",
    "r":"Down the rabbit hole Such a strange place Into a world Were your gone with no trace
",
    "s":"I never put away all of these socks, there's just something so final about putting away all the socks. When I close the drawer after putting away the clothes, its like saying remain here for awhile, for I do not plan to wear you again for some time",
    "t":"I have never understood why anyone would roast the turkey and shuck the clams and crisp the croutons and shell the peas and candy the sweets and compote the cranberries and bake the pies and clear the table and wash the dishes and fall into bed when they could sit back and enjoy a hamburger.",
    "u":"I own an umbrella A black umbrella With all the colors of the rainbow underneath, I own an umbrella Which protects me from the rain and the bad days, I own an umbrella Dark outside and colorful inside",
    "v":"I saw this specific  vest There was only one left The look of it being priceless It was just the right size It definitely caught my eyes The  vest had this certain look All you have to do reflect on took Of course I had to have the jeans The one’s that make your legs look lean I didn’t want the jeans to be tight But have the look that will be out of sight The  vest being blue It stands for my heart being true",
    "w":"A watch upon your wrist, a fashion statement made, It tells the world your style, with every move displayed. A fashion accessory, both functional and chic, It speaks of your personality, your essence, your mystique. From classic to modern, from leather to gold, A watch can set the tone, a story to be told. It’s more than just a timepiece, it’s a symbol of your grace, A reflection of your character, a statement of your pace. A watch can be a statement, a bold and daring choice, Or it can be understated, a whisper of a voice.",
    "x":"What is important for people to know?  That I’m human.  That I’m becoming more transparent. An x-ray Makes clear what resides in the body. It is a question  That opens an answer.  It is an order Of understanding. Beneath a microscope, among The most beautiful things  You can see: Yellow protein crystal.  How it spikes and turns, Spirals like a curly girl’s hair.",
    "y":"am a yoyo, gloom and bloom, up and down, I shine the up, and ride the down, the child playing the string",
    "z":"There is no need for zippers in the future. We only use buttons. Easier to undo, they require only one swift motion while zippers require two. some say we digress, but we simply resort to practicality. a zipper can get caught, a button just falls off. a zipper can lose teeth, a button just falls off. a zipper eventually rusts, a button just falls off. But we can always just sew the button back on. That is why we choose buttons in the future."
    }
  end
end
